name: Reusable Deploy
on: 
  workflow_call:
    inputs:
      artifact-name:
        type: string
        description: The name of the deployable artifact files
        required: true
        default: dist
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls
      - name: Output Information
        run: echo "Deploying & Uploading"