name: Reusable Deploy
on: 
  workflow_call:
    inputs:
      artifact-name:
        type: string
        description: The name of the deployable artifact files
        required: true
        default: dist
    outputs:
      result: 
        description: Result of the deployment operation
        value: ${{ jobs.deploy.outputs.deploy-result }}
    secrets:
      github-token:
        required: true
jobs:
  deploy:
    outputs:
      deploy-result: ${{ steps.set-result.outputs.deploy-job-outcome }}
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls
      - name: Output Information
        run: echo "Deploying & Uploading"
      - name: Set Result Output
        id: set-result
        run: echo "deploy-job-outcome=success" >> $GITHUB_OUTPUT